### ISSUE TITLE
Huidige release werkt niet met JDK 21

### ISSUE THREAD

**Issue by pjmaenh** [HoGentTIN/sql-injection-tester#2]
Error: LinkageError occurred while loading main class be.hogent.sqlinjectiontester.App
        java.lang.UnsupportedClassVersionError: be/hogent/sqlinjectiontester/App has been compiled by a more recent version of the Java Runtime (class file version 66.0), this version of the Java Runtime only recognizes class file versions up to 65.0

**Comment by MartenBE** [comment]
Should be fixed with https://github.com/HoGentTIN/sql-injection-tester/releases/tag/2024-10-07-v1.
